# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8534a4f345636f08f04fdefd47bdec08aa7fe8cfcc3c188a14dae2ccb6df77cc4ca1d647ccf0c8e8a1ef2817d4c2163a38ddccc4960507f4f2f7a0f76c19cba

test:
  secret_key_base: 1e976c2e541d135c73abf954d7c797b5d875ff8eb111f44815c3ad2295c582210433a82bef7c632e8fbf7f71c84d30e64b4051666d886338cbfa189553cd3799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
